name: 游냍 Bug Report
description: Rapport칠r en fejl i et script
title: "[Bug] <Kort beskrivelse af fejlen>"
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    attributes:
      label: "Fejlbeskrivelse"
      description: "Beskriv fejlen s친 detaljeret som muligt."
      placeholder: "Hvad sker der? Hvad forventede du, der ville ske?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "S친dan genskabes fejlen"
      description: "Trin for at reproducere fejlen."
      placeholder: |
        1. Start serveren
        2. Udf칮r <kommando/handling>
        3. Fejlen opst친r
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Forventet opf칮rsel"
      description: "Hvad burde der ske?"
      placeholder: "Skriv hvad der burde ske i stedet."

  - type: textarea
    attributes:
      label: "Logs & fejlmeddelelser"
      description: "Inds칝t relevante fejl fra konsollen/serveren."
      render: shell

  - type: input
    attributes:
      label: "FiveM & OS Info"
      description: "Hvilken server-art og OS k칮rer du p친?"
      placeholder: "Windows/Linux + FiveM artifact version"

  - type: checkboxes
    attributes:
      label: "Ekstra"
      options:
        - label: "Jeg har s칮gt i eksisterende issues"
          required: true
        - label: "Jeg har testet p친 den nyeste version af scriptet"
          required: true
