blank_issues_enabled: false
contact_links:
  - name: Dokumentation
    url: https://docs.nn-development.dk
    about: Søg alt info op her 🥶
  - name: Discord
    url: https://discord.nn-development.dk
    about: Kontakt community her.
