name: ✨ Feature Request
description: Foreslå en ny funktion eller ændring
title: "[Feature] <Beskrivelse af ønsket funktion>"
labels: ["enhancement", "feature request"]
body:
  - type: textarea
    attributes:
      label: "Beskrivelse af funktionen"
      description: "Hvad skal denne feature gøre?"
      placeholder: "Forklar funktionaliteten"

  - type: textarea
    attributes:
      label: "Hvorfor er dette nyttigt?"
      description: "Beskriv hvordan dette forbedrer scriptet."
      placeholder: "Hvorfor er det nødvendigt?"

  - type: textarea
    attributes:
      label: "Alternativer"
      description: "Er der andre måder at opnå dette på?"
      placeholder: "Er der workarounds?"

  - type: checkboxes
    attributes:
      label: "Ekstra"
      options:
        - label: "Jeg har søgt i eksisterende issues"
          required: true
