name: 🔧 Forbedring af eksisterende funktion
description: Optimering eller justering af nuværende funktionalitet
title: "[Enhancement] <Beskrivelse>"
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: "Beskrivelse af forbedringen"
      description: "Hvad skal forbedres?"
      placeholder: "F.eks. ydeevneoptimering, UI-justeringer"

  - type: textarea
    attributes:
      label: "Hvorfor?"
      description: "Hvorfor er dette en vigtig forbedring?"
      placeholder: "Forklar behovet"

  - type: checkboxes
    attributes:
      label: "Ekstra"
      options:
        - label: "Jeg har søgt i eksisterende issues"
          required: true
