name: ❓ Support / Spørgsmål
description: Få hjælp til et problem
title: "[Support] <Beskrivelse>"
labels: ["question", "help wanted"]
body:
  - type: textarea
    attributes:
      label: "Hvad har du brug for hjælp til?"
      description: "Beskriv dit problem eller spørgsmål."
      placeholder: "Beskriv problemet detaljeret."

  - type: input
    attributes:
      label: "FiveM & OS Info"
      description: "Hvilken server-art og OS kører du på?"
      placeholder: "Windows/Linux + FiveM artifact version"

  - type: checkboxes
    attributes:
      label: "Ekstra"
      options:
        - label: "Jeg har søgt i eksisterende issues"
          required: true
        - label: "Jeg har testet på den nyeste version"
          required: true
